# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1951c94fb83990bd21d2659d2351334e3266dc88317c09d5dc7d6f6eb817017b2b48d7d7198d02ed97122c7d137935831a48dd7a499191272a7996e6cb5928d1

test:
  secret_key_base: 2180ad8f59b3b826794699a8efabb644e94be4cd96cd9656a8c9b4ba1a43a58139e6b613e55567df26881f3b8c0b4a4a32d13b78f4f32c8eb01920678c387b22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
